using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Wms.Infrastructure.Data;

#nullable disable

namespace Wms.API.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260801190000_InitialPostgres")]
public partial class InitialPostgres : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE IF NOT EXISTS "PosicoesArmazem"
            (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Corredor" text NOT NULL,
                "Prateleira" integer NOT NULL,
                "Nivel" integer NOT NULL,
                "Ocupada" boolean NOT NULL
            );

            CREATE TABLE IF NOT EXISTS "Usuarios"
            (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Username" text NOT NULL,
                "PasswordHash" text NOT NULL,
                "Role" text NOT NULL
            );

            CREATE TABLE IF NOT EXISTS "HistoricosMovimentacao"
            (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Sku" text NOT NULL,
                "ProdutoNome" text NOT NULL,
                "TipoMovimentacao" text NOT NULL,
                "Quantidade" integer NOT NULL,
                "EnderecoGalpao" text NOT NULL,
                "DataHora" timestamp with time zone NOT NULL,
                "UsuarioResponsavel" text NOT NULL,
                "Arquivado" boolean NOT NULL
            );

            CREATE TABLE IF NOT EXISTS "Produtos"
            (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Nome" text NOT NULL,
                "Sku" text NOT NULL,
                "Quantidade" integer NOT NULL,
                "Peso" double precision NOT NULL,
                "EstoqueMinimo" integer NOT NULL,
                "PosicaoArmazemId" integer NULL
            );

            ALTER TABLE "Produtos"
                DROP COLUMN IF EXISTS "PoshemId";

            DO $$
            BEGIN
                IF NOT EXISTS
                (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'FK_Produtos_PosicoesArmazem_PosicaoArmazemId'
                )
                THEN
                    ALTER TABLE "Produtos"
                    ADD CONSTRAINT "FK_Produtos_PosicoesArmazem_PosicaoArmazemId"
                    FOREIGN KEY ("PosicaoArmazemId")
                    REFERENCES "PosicoesArmazem" ("Id")
                    ON DELETE SET NULL;
                END IF;
            END
            $$;

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Produtos_Sku"
                ON "Produtos" ("Sku");

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Produtos_PosicaoArmazemId"
                ON "Produtos" ("PosicaoArmazemId")
                WHERE "PosicaoArmazemId" IS NOT NULL;

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Usuarios_Username"
                ON "Usuarios" ("Username");

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_PosicoesArmazem_Corredor_Prateleira_Nivel"
                ON "PosicoesArmazem" ("Corredor", "Prateleira", "Nivel");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DROP TABLE IF EXISTS "Produtos";
            DROP TABLE IF EXISTS "HistoricosMovimentacao";
            DROP TABLE IF EXISTS "Usuarios";
            DROP TABLE IF EXISTS "PosicoesArmazem";
            """);
    }
}
